ALTER TABLE GROUPE ADD (
     CONSTRAINT FK_GROUPE_PARTICIPANT
          FOREIGN KEY (NUM_PARTICIPANT)
               REFERENCES PARTICIPANT (NUM_PARTICIPANT));

ALTER TABLE INDISPONIBILITE ADD (
     CONSTRAINT FK_INDISPONIBILITE_PARTICIPANT
          FOREIGN KEY (NUM_PARTICIPANT)
               REFERENCES PARTICIPANT (NUM_PARTICIPANT));

ALTER TABLE EVENEMENT ADD (
     CONSTRAINT FK_EVENEMENT_PERIODICITE
          FOREIGN KEY (NUM_PERIODICITE)
               REFERENCES PERIODICITE (NUM_PERIODICITE));

ALTER TABLE EVENEMENT ADD (
     CONSTRAINT FK_EVENEMENT_AGENDA
          FOREIGN KEY (NUM_AGENDA)
               REFERENCES AGENDA (NUM_AGENDA));

ALTER TABLE EVENEMENT ADD (
     CONSTRAINT FK_EVENEMENT_PARTICIPANT
          FOREIGN KEY (NUM_PARTICIPANT)
               REFERENCES PARTICIPANT (NUM_PARTICIPANT));

ALTER TABLE GROUPE_UTILISATEUR ADD (
     CONSTRAINT FK_GROUPE_UTILISATEUR_GROUPE
          FOREIGN KEY (NUM_GROUPE)
               REFERENCES GROUPE (NUM_GROUPE));

ALTER TABLE GROUPE_UTILISATEUR ADD (
     CONSTRAINT FK_GROUPE_UTILISATEUR_PARTICIP
          FOREIGN KEY (NUM_PARTICIPANT)
               REFERENCES PARTICIPANT (NUM_PARTICIPANT));

ALTER TABLE ABSENCE ADD (
     CONSTRAINT FK_ABSENCE_OCCURRENCE
          FOREIGN KEY (NUM_EVENEMENT, NUM_OCCURRENCE)
               REFERENCES OCCURRENCE (NUM_EVENEMENT, NUM_OCCURRENCE));

ALTER TABLE ABSENCE ADD (
     CONSTRAINT FK_ABSENCE_PARTICIPANT
          FOREIGN KEY (NUM_PARTICIPANT)
               REFERENCES PARTICIPANT (NUM_PARTICIPANT));

ALTER TABLE PARTICIPATION ADD (
     CONSTRAINT FK_PARTICIPATION_EVENEMENT
          FOREIGN KEY (NUM_EVENEMENT)
               REFERENCES EVENEMENT (NUM_EVENEMENT));

ALTER TABLE PARTICIPATION ADD (
     CONSTRAINT FK_PARTICIPATION_PARTICIPANT
          FOREIGN KEY (NUM_PARTICIPANT)
               REFERENCES PARTICIPANT (NUM_PARTICIPANT));