-- -----------------------------------------------------------------------------
--       VUE : PARTICIPANT_UTILISATEUR
-- -----------------------------------------------------------------------------

CREATE VIEW PARTICIPANT_UTILISATEUR  (NUM_PARTICIPANT, NOM_PARTICIPANT, PRENOM_PARTICIPANT, DATE_NAISS_PARTICIPANT, SEXE_PARTICIPANT, MAIL_PARTICIPANT, TEL_PARTICIPANT, TYPE_PARTICIPANT, LOGIN, MDP, DATE_CREA_COMPTE, STATUT_COMPTE, TYPE_UTILISATEUR) AS
SELECT PARTICIPANT.NUM_PARTICIPANT, PARTICIPANT.NOM_PARTICIPANT, PARTICIPANT.PRENOM_PARTICIPANT, PARTICIPANT.DATE_NAISS_PARTICIPANT, PARTICIPANT.SEXE_PARTICIPANT, PARTICIPANT.MAIL_PARTICIPANT, PARTICIPANT.TEL_PARTICIPANT, PARTICIPANT.TYPE_PARTICIPANT, PARTICIPANT.LOGIN, PARTICIPANT.MDP, PARTICIPANT.DATE_CREA_COMPTE, PARTICIPANT.STATUT_COMPTE, PARTICIPANT.TYPE_UTILISATEUR
FROM PARTICIPANT ;

-- -----------------------------------------------------------------------------
--       VUE : PARTICIPANT_INVITE
-- -----------------------------------------------------------------------------

CREATE VIEW PARTICIPANT_INVITE  (NUM_PARTICIPANT, NOM_PARTICIPANT, PRENOM_PARTICIPANT, DATE_NAISS_PARTICIPANT, SEXE_PARTICIPANT, MAIL_PARTICIPANT, TEL_PARTICIPANT, TYPE_PARTICIPANT) AS
SELECT PARTICIPANT.NUM_PARTICIPANT, PARTICIPANT.NOM_PARTICIPANT, PARTICIPANT.PRENOM_PARTICIPANT, PARTICIPANT.DATE_NAISS_PARTICIPANT, PARTICIPANT.SEXE_PARTICIPANT, PARTICIPANT.MAIL_PARTICIPANT, PARTICIPANT.TEL_PARTICIPANT, PARTICIPANT.TYPE_PARTICIPANT
FROM PARTICIPANT ;