DROP TABLE GROUPE_UTILISATEUR CASCADE CONSTRAINTS ; 

DROP TABLE ABSENCE CASCADE CONSTRAINTS ; 

DROP TABLE PARTICIPATION CASCADE CONSTRAINTS ;

DROP TABLE GROUPE CASCADE CONSTRAINTS ;

DROP TABLE INDISPONIBILITE CASCADE CONSTRAINTS ;

DROP TABLE OCCURRENCE CASCADE CONSTRAINTS ;

DROP TABLE EVENEMENT CASCADE CONSTRAINTS ;

DROP TABLE AGENDA CASCADE CONSTRAINTS ;

DROP TABLE PERIODICITE CASCADE CONSTRAINTS ;

DROP TABLE PARTICIPANT CASCADE CONSTRAINTS ;        