DROP INDEX I_FK_GROUPE_PARTICIPANT ; 

DROP INDEX I_FK_INDISPONIBILITE_PARTICIPA ; 

DROP INDEX I_FK_EVENEMENT_PERIODICITE ;

DROP INDEX I_FK_EVENEMENT_AGENDA ;

DROP INDEX I_FK_EVENEMENT_PARTICIPANT ;

DROP INDEX I_FK_OCCURRENCE_EVENEMENT ;

DROP INDEX I_FK_GROUPE_UTILISATEUR_GROUPE ;

DROP INDEX I_FK_GROUPE_UTILISATEUR_GROUPE ;

DROP INDEX I_FK_GROUPE_UTILISATEUR_PARTIC ;

DROP INDEX I_FK_ABSENCE_OCCURRENCE ;

DROP INDEX I_FK_ABSENCE_PARTICIPANT ;

DROP INDEX I_FK_PARTICIPATION_EVENEMENT ;

DROP INDEX I_FK_PARTICIPATION_PARTICIPANT ;